### PR TITLE
Update apps.md with missing step for logout flow.

### PR DESCRIPTION
**Pull request by tiagobernardo351**
Added missing step in the logout flow.
It was indicated to use the action GetExternalLogoutURL() to get the logout URL but the return value was then never used in the last RedirectURL element in the flow.

### CODE REVIEW

**Comment by tiagobernardo351** [comment]
I read, understood and accept the OutSystems CLA.

**Comment by tiagobernardo351** [comment]
I read, understood and accept the OutSystems CLA

> Hello @tiagobernardo351 👋
> 
> Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the 📝 [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
> 
> After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

**Comment by tiagobernardo351** [comment]
I read, understood and accept the OutSystems CLA

> Hello @tiagobernardo351 👋
> 
> Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the 📝 [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
> 
> After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

**Review by OS-oliviaannemichael — APPROVED** [review]

**Comment by rmlos** [comment]
Fixed manually in VSC.

**Pull request merged**
